<?php
/**
 * Filesystem: backup directory creation/hardening and path validation.
 *
 * @package SimpleDBBackup
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Owns everything about *where* backups live and guarantees that any
 * filename we act on is confined to the managed backup directory.
 */
class Simple_DB_Backup_Filesystem {

	/**
	 * Allowed backup file extensions.
	 */
	const ALLOWED_EXTENSIONS = array( 'sql', 'sql.gz' );

	/**
	 * Absolute path to the managed backup directory (no trailing slash).
	 *
	 * @return string
	 */
	public static function get_backup_dir() {
		return self::dir_for( Simple_DB_Backup_Settings::get_options() );
	}

	/**
	 * Resolve the backup directory for a given options array.
	 *
	 * A non-empty `backup_path` (an absolute path) wins; otherwise the default
	 * unguessable folder under wp-content/uploads is used.
	 *
	 * @param array<string,mixed> $options Options array.
	 * @return string Absolute path, no trailing slash.
	 */
	public static function dir_for( array $options ) {
		$custom = isset( $options['backup_path'] ) ? trim( (string) $options['backup_path'] ) : '';
		if ( '' !== $custom ) {
			return untrailingslashit( wp_normalize_path( $custom ) );
		}

		$uploads = wp_get_upload_dir();
		$name    = ! empty( $options['backup_dirname'] ) ? $options['backup_dirname'] : 'sdb-backups';

		return untrailingslashit( $uploads['basedir'] ) . '/' . $name;
	}

	/**
	 * Whether a normalized absolute path lies inside the WordPress install
	 * (and so is potentially reachable over the web).
	 *
	 * @param string $path Normalized absolute path.
	 * @return bool
	 */
	public static function is_within_webroot( $path ) {
		$root = untrailingslashit( wp_normalize_path( ABSPATH ) );
		$path = untrailingslashit( wp_normalize_path( $path ) );
		return $path === $root || 0 === strpos( $path . '/', $root . '/' );
	}

	/**
	 * Create the default backup directory if needed and (re)write its guards.
	 *
	 * @return bool True if the directory exists and is writable afterwards.
	 */
	public static function ensure_protected_dir() {
		return self::prepare_dir( self::get_backup_dir() );
	}

	/**
	 * Create a specific directory if needed and (re)write its protection files.
	 *
	 * @param string $dir Absolute directory path.
	 * @return bool True if the directory exists and is writable afterwards.
	 */
	public static function prepare_dir( $dir ) {
		if ( '' === $dir ) {
			return false;
		}

		if ( ! is_dir( $dir ) ) {
			wp_mkdir_p( $dir );
		}

		if ( ! is_dir( $dir ) ) {
			return false;
		}

		self::write_protection_files( $dir );

		return is_writable( $dir );
	}

	/**
	 * Move all backup files from one directory to another.
	 *
	 * @param string $from Source directory.
	 * @param string $to   Destination directory.
	 */
	public static function move_backups( $from, $to ) {
		$from = untrailingslashit( (string) $from );
		$to   = untrailingslashit( (string) $to );

		if ( '' === $from || '' === $to || $from === $to || ! is_dir( $from ) || ! is_dir( $to ) ) {
			return;
		}

		foreach ( (array) scandir( $from ) as $entry ) {
			if ( ! self::has_allowed_extension( $entry ) ) {
				continue;
			}
			$src = $from . '/' . $entry;
			$dst = $to . '/' . $entry;
			if ( ! is_file( $src ) ) {
				continue;
			}
			if ( ! @rename( $src, $dst ) ) { // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
				if ( @copy( $src, $dst ) ) { // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
					wp_delete_file( $src );
				}
			}
		}
	}

	/**
	 * Write/refresh the Apache, IIS and directory-index guards.
	 *
	 * @param string $dir Absolute backup directory path.
	 */
	private static function write_protection_files( $dir ) {
		$htaccess = "# Generated by Simple DB Backup. Deny all direct web access.\n"
			. "<IfModule mod_authz_core.c>\n  Require all denied\n</IfModule>\n"
			. "<IfModule !mod_authz_core.c>\n  Order allow,deny\n  Deny from all\n</IfModule>\n";

		$webconfig = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
			. "<configuration>\n  <system.webServer>\n    <authorization>\n"
			. "      <deny users=\"*\" />\n    </authorization>\n"
			. "  </system.webServer>\n</configuration>\n";

		$silence = "<?php\n// Silence is golden.\n";

		self::put_file( $dir . '/.htaccess', $htaccess );
		self::put_file( $dir . '/web.config', $webconfig );
		self::put_file( $dir . '/index.php', $silence );
		self::put_file( $dir . '/index.html', '' );
	}

	/**
	 * Write a protection file only if missing or changed, then lock it down.
	 *
	 * @param string $path     Absolute file path.
	 * @param string $contents File contents.
	 */
	private static function put_file( $path, $contents ) {
		$existing = is_readable( $path ) ? file_get_contents( $path ) : null;
		if ( $existing !== $contents ) {
			file_put_contents( $path, $contents, LOCK_EX );
		}
		@chmod( $path, 0640 ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
	}

	/**
	 * Resolve a user-supplied backup name to a safe absolute path inside the
	 * managed directory, or false if it escapes the directory / is not allowed.
	 *
	 * Closes the path-traversal arbitrary file download/delete vectors.
	 *
	 * @param string $name Requested file name.
	 * @return string|false Absolute path or false.
	 */
	public static function resolve_backup_path( $name ) {
		$name = basename( wp_unslash( (string) $name ) );

		if ( '' === $name || ! self::has_allowed_extension( $name ) ) {
			return false;
		}

		$dir  = self::get_backup_dir();
		$path = $dir . '/' . $name;

		$real_dir  = realpath( $dir );
		$real_path = realpath( $path );

		if ( false === $real_dir || false === $real_path ) {
			return false;
		}

		// Must be a regular file that physically lives inside the backup dir.
		if ( ! is_file( $real_path ) ) {
			return false;
		}

		$prefix = $real_dir . DIRECTORY_SEPARATOR;
		if ( 0 !== strncmp( $real_path, $prefix, strlen( $prefix ) ) ) {
			return false;
		}

		return $real_path;
	}

	/**
	 * Whether a filename ends in one of the allowed backup extensions.
	 *
	 * @param string $name File name.
	 * @return bool
	 */
	public static function has_allowed_extension( $name ) {
		$name = strtolower( $name );
		foreach ( self::ALLOWED_EXTENSIONS as $ext ) {
			if ( substr( $name, -( strlen( $ext ) + 1 ) ) === '.' . $ext ) {
				return true;
			}
		}
		return false;
	}

	/**
	 * List existing backups, newest first.
	 *
	 * @return array<int,array{name:string,path:string,size:int,mtime:int}>
	 */
	public static function list_backups() {
		$dir = self::get_backup_dir();
		if ( ! is_dir( $dir ) ) {
			return array();
		}

		$backups = array();
		foreach ( (array) scandir( $dir ) as $entry ) {
			if ( '.' === $entry || '..' === $entry || ! self::has_allowed_extension( $entry ) ) {
				continue;
			}
			$path = $dir . '/' . $entry;
			if ( ! is_file( $path ) ) {
				continue;
			}
			$backups[] = array(
				'name'  => $entry,
				'path'  => $path,
				'size'  => (int) filesize( $path ),
				'mtime' => (int) filemtime( $path ),
			);
		}

		usort(
			$backups,
			static function ( $a, $b ) {
				return $b['mtime'] <=> $a['mtime'];
			}
		);

		return $backups;
	}

	/**
	 * MD5 checksum of a backup file, cached so large files are not re-hashed on
	 * every page load. The cache key includes size and mtime, so it invalidates
	 * automatically if the file ever changes.
	 *
	 * @param string $path Absolute file path.
	 * @return string 32-character hex digest, or '' if unavailable.
	 */
	public static function checksum( $path ) {
		if ( '' === $path || ! is_file( $path ) ) {
			return '';
		}

		$key    = 'sdb_md5_' . md5( $path . '|' . filesize( $path ) . '|' . filemtime( $path ) );
		$cached = get_transient( $key );
		if ( is_string( $cached ) ) {
			return $cached;
		}

		$hash = md5_file( $path );
		$hash = is_string( $hash ) ? $hash : '';

		set_transient( $key, $hash, WEEK_IN_SECONDS );

		return $hash;
	}

	/**
	 * Delete backups beyond the retention limit (keeps the newest $max).
	 *
	 * @param int $max Number of backups to keep.
	 */
	public static function enforce_retention( $max ) {
		$max     = max( 1, (int) $max );
		$backups = self::list_backups();

		foreach ( array_slice( $backups, $max ) as $backup ) {
			$path = self::resolve_backup_path( $backup['name'] );
			if ( false !== $path ) {
				wp_delete_file( $path );
			}
		}
	}
}
